### ISSUE TITLE
[13] Melakukan Pencarian Literatur Berdasarkan Judul, Penulis, Penerbit, atau Jenis Literatur Tertentu

### ISSUE THREAD

**Issue by akhdakhz03** [apap-ekstensi-2018/TA_D#14]
Initial Page: ​/literatur/cari
Form Request: ​GET,
/literatur/cari?judul={judulBuku}&penulis={namaPenulis}&penerbit={namaPenerbit}&jeni
s={jenisLiteratur}
Response Page:
/literatur/cari?judul={judulBuku}&penulis={namaPenulis}&penerbit={namaPenerbit}&jeni
s={jenisLiteratur}
Role: ​Semua Pegawai, Mahasiswa
Poin: ​10
Pada fitur ini anda diminta untuk melakukan pencarian literatur berdasarkan judul, penulis,
penerbit, atau jenis literatur. Pada halaman “/literatur/cari” akan ditampilkan field yang
dibutuhkan untuk melakukan pencarian tersebut, yaitu:
● Judul Buku
● Nama Penulis
● Nama Penerbit
● Jenis Literatur
Semua filter pencarian bersifat opsional, jadi tidak diwajibkan untuk diisi. Anda dibebaskan
dalam mekanisme pencarian tersebut. Halaman ini dapat diakses oleh semua pegawai dan
mahasiswa.

**Comment by KurniawanHendiW** [comment]
pak ane buat chain drop down yak? @akhdakhz03

**Comment by KurniawanHendiW** [comment]
Done
