### ISSUE TITLE
[2] Logout

### ISSUE THREAD

**Issue by akhdakhz03** [apap-ekstensi-2018/TA_D#3]
Initial Page:​ -
Form Request: ​POST, /logout
Response Page:​ /login
Role: ​Semua Pegawai, Mahasiswa
Poin: ​5
Pada fitur ini anda diminta untuk membuat sistem logout. Sistem ini dapat diakses oleh
mahasiswa dan pegawai yang telah terverifikasi berhasil masuk ke sistem. Jika tombol logout
ditekan, maka data session dan hak akses membuka halaman-halaman yang terdapat pada sistem
(kecuali login) akan dihapus dan sistem menampilkan halaman login.

**Comment by ganigemilar** [comment]
udah solved coy
