### ISSUE TITLE
[3] Menambahkan Literatur

### ISSUE THREAD

**Issue by akhdakhz03** [apap-ekstensi-2018/TA_D#4]
Initial Page:​ /literatur/tambah
Request Method: ​POST, /literatur/tambah
Response Page:​ /literatur/tambah
Role:​ Staf
Poin​: 5
Pada fitur ini anda diminta untuk melakukan penambahan literatur pada sistem. Pada halaman
“/literatur/tambah”, sistem akan menampilkan form dengan ketentuan input form field, yaitu:
● Judul
● Penulis
● Penerbit
● Jenis Literatur
● Jumlah (merepresentasikan jumlah literatur, bukan jumlah yang tersedia)
Terkait tipe input form, kami bebaskan. Ketika tombol submit ditekan, maka sistem akan
memvalidasi input pengguna dan memvalidasi apakah data literatur tersebut sudah ada atau
belum. Apabila belum, maka data dimasukkan pada database dan menampilkan halaman
konfirmasi bahwa penambahan data literatur telah berhasil dimasukkan. Dan jika data sudah ada
maka akan muncul informasi bahwa penambahan data literatur gagal dimasukkan. Halaman ini
hanya dapat diakses oleh staf.

**Comment by KurniawanHendiW** [comment]
Done
