### ISSUE TITLE
[4] Mengubah Jumlah Literatur

### ISSUE THREAD

**Issue by akhdakhz03** [apap-ekstensi-2018/TA_D#5]
Initial Page:​ /literatur/ubah/{id_literatur}
Request Method: ​POST, /literatur/ubah/{id_literatur}
Response Page:​ /literatur/ubah/{id_literatur}
Role:​ Staf
Poin​: 5
Pada fitur ini anda diminta untuk melakukan perubahan data literatur yang ada pada sistem. Pada
halaman “/literatur/ubah/{id_literatur}”, sistem akan menampilkan form dengan ketentuan input
form field yang sama seperti penambahan literatur, namun dengan kondisi field yang telah terisi
dengan data literatur yang ingin diubah.
Ketika tombol submit ditekan, maka sistem akan memvalidasi data baru yang di-input pengguna.
Jika valid, maka data pada database akan di-update dan menampilkan halaman konfirmasi
bahwa perubahan data literatur telah berhasil dimasukkan. Dan jika gagal, maka akan muncul
informasi bahwa perubahan data literatur gagal dilakukan. Halaman ini hanya dapat diakses oleh
staf.

**Comment by ibnvakbar** [comment]
Apakah ada ketentuan tentang validasi data?

**Comment by akhdakhz03** [comment]
validasi frontend dan backend opsional. 
utamakan fungsi update bisa berjalan.

**Comment by KurniawanHendiW** [comment]
Bagus lagi ada validasi @ibnvakbar

**Comment by ibnvakbar** [comment]
tinggal view belum rapi
