### ISSUE TITLE
[5] Melihat Seluruh Literatur

### ISSUE THREAD

**Issue by akhdakhz03** [apap-ekstensi-2018/TA_D#6]
Initial Page:​ -
Request Method: ​GET, /literatur/viewall
Response Page:​ /literatur/viewall
Role:​ Semua Pegawai, Mahasiswa
Poin​: 5
Pada fitur ini anda diminta untuk menampilkan seluruh data literatur yang terdapat pada sistem.
Pada halaman “/literatur/viewall” akan ditampilkan tabel yang berisi list dari literatur yang terdapat pada sistem. Kami membebaskan data apa saja yang dapat ditampilkan pada tabel ini.
Halaman ini dapat diakses oleh semua pegawai dan mahasiswa.

**Comment by herlenadita** [comment]
Rampung yo pak
