### ISSUE TITLE
[6] Melihat Detail Literatur

### ISSUE THREAD

**Issue by akhdakhz03** [apap-ekstensi-2018/TA_D#7]
Initial Page:​ -
Request Method: ​GET, /literatur/view/{id_literatur}
Response Page:​ /literatur/view/{id_literatur}
Role:​ Semua Pegawai, Mahasiswa
Poin​: 5
Pada fitur ini anda diminta untuk menampilkan detail suatu literatur. Pada halaman
“/literatur/view/{id_literatur}” akan ditampilkan data-data detail literatur tersebut, yaitu:
● Id Literatur
● Judul
● Penulis
● Penerbit
● Jenis Literatur
● Jumlah Tersedia
Jumlah yang ditampilkan pada halaman ini berbeda dengan jumlah pada halaman penambahan
literatur, pada halaman ini jumlah yang ditampilkan adalah jumlah yang tersedia​. Halaman
ini dapat diakses oleh semua pegawai dan mahasiswa.

**Comment by ibnvakbar** [comment]
Tinggal view belum rapi
