### ISSUE TITLE
[7] Menghapus Data Literatur

### ISSUE THREAD

**Issue by akhdakhz03** [apap-ekstensi-2018/TA_D#8]
Initial Page:​ /literatur/view/{id_literatur}
Request Method: ​POST, ​/literatur/hapus/{id_literatur}
Response Page: ​/literatur/hapus/{id_literatur}
Role: ​Staf
Poin​: 5
Pada fitur ini anda diminta untuk melakukan penghapusan data literatur yang terdapat pada
sistem. Fitur ini dapat diakses oleh staf dengan menekan tombol hapus yang terdapat pada
halaman “/literatur/view/{id_literatur}”. Jika tombol hapus diklik, maka sistem akan menghapus
literatur tersebut dan menampilkan halaman konfirmasi bahwa penghapusan ruang telah berhasil
dilakukan. Halaman ini hanya dapat diakses oleh staf.

**Comment by KurniawanHendiW** [comment]
@herlenadita mbak ini link buat hapusnya, buat ditaruh di action datatables

**Comment by herlenadita** [comment]
@KurniawanHendiW siap pak

**Comment by KurniawanHendiW** [comment]
done
