### ISSUE TITLE
[8] Mengajukan Peminjaman Literatur

### ISSUE THREAD

**Issue by akhdakhz03** [apap-ekstensi-2018/TA_D#9]
Initial Page: ​/peminjaman/tambah
Form Request: ​POST, /peminjaman/tambah
Response Page:​ /peminjaman/tambah
Role: ​Dosen, Mahasiswa
Poin: ​5
Pada fitur ini anda diminta untuk membuat sistem pengajuan peminjaman literatur, proses
peminjaman ini membutuhkan web service dari SISurat pada kasus tertentu. Pada halaman
“/peminjaman”, sistem akan menampilkan form dengan ketentuan input form field, yaitu:
● Id Literatur
● Tanggal Peminjaman
● Tanggal Pengembalian
● Id Surat
Terkait tipe input form, kami bebaskan. Sedangkan untuk field Id Surat, data tersebut adalah id
surat rekomendasi dari dosen yang hanya dibutuhkan ketika literatur yang dipinjam adalah
Skripsi, Tesis, atau Disertasi​.
Ketika tombol submit ditekan, maka sistem akan memvalidasi apakah literatur tersebut tersedia
pada waktu yang telah ditentukan. Dan apabila tersedia, maka data dimasukkan pada database
dan menampilkan halaman konfirmasi bahwa pengajuan peminjaman literatur telah berhasil
dilakukan. Dan jika gagal maka terdapat informasi bahwa pengajuan peminjaman literatur gagal
dilakukan. Halaman ini dapat diakses oleh mahasiswa dan dosen.
**Khusus untuk peminjaman Skripsi, Tesis, dan Disertasi, sistem harus melakukan validasi id
surat, apakah surat tersebut sudah disetujui, nama pada surat tersebut sesuai dengan pengguna
yang sedang login, dan jenis surat tersebut sesuai untuk peminjaman literatur**. Mekanisme
validasi tersebut hanya contoh, anda dibebaskan mengimplementasi mekanisme lain, namun
harus tetap sesuai dengan tujuan yang telah dijelaskan.

**Comment by KurniawanHendiW** [comment]
Bagian yang dibold jangan lupa @akhdakhz03
